<?php $brandNames = Mage::helper('vendorinventory')->getBrandNames(); ?>
<?php echo Mage::getStoreConfig('banner/general/banner_text'); ?>
<div id="configuration-container">
    <select name="brand_dropdown" id="brand-dropdown">
        <option value="">Select Brand</option>
        <?php foreach ($brandNames as $_k => $_v): ?>
            <option value="<?php echo $_k ?>"><?php echo $_v; ?></option>
        <?php endforeach; ?>
    </select>
    <div id="file-upload-container" style="display:inline"></div>
</div>
<div id="table-container"></div>
<script type="text/javascript">
    document.observe('dom:loaded', function () {
        var FORM_KEY = '<?php echo $this->getFormKey() ?>'
        options = {
            'containerId': 'configuration-container',
            'url': '<?php echo $this->getUrl('*/*/getheaders') ?>',
            'saveUrl': '<?php echo $this->getUrl('*/*/save') ?>',
            'form_key': FORM_KEY,
            'getConfigUrl': '<?php echo $this->getUrl('*/*/getconfiguration') ?>'
        }
        var config = new Configuration(options);
    });
</script>