<button id="add-event">Add Event</button>
<a id="save-events">Save Events</a>
<div id="event-tables-container"></div>
<?php //$config_id = ($this->getRequest()->getParam('config_id'));


// print_r(Mage::getModel('outlook/event')->getCollection()->addFieldToFilter('config_id',$config_id)->getData());
?>
<script>
    document.observe('dom:loaded', function () {
        eventManager = new EventManager('add-event', 'event-tables-container');
        $("save-events").observe("click", function() {
            eventManager.sendEventData();
        });
    });
</script>