<div id="event-container">
    <button type="button" id="add-event" class="add-event">Add Event</button>
    <button type="button" id="save-event" class="save-event">Save Events</button>
    <div id="event-table-container" class="event-container-table"></div>
</div>

<script>
    document.observe('dom:loaded', function () {
        var saveUrl = '<?php echo $this->getUrl('*/*/saveEvent'); ?>'
        var fetchUrl = '<?php echo $this->getUrl('*/*/fetchEvent'); ?>'
        var eventManager = new EventManager(
            'event-container', 
            'add-event', 
            'save-event', 
            'event-table-container', 
            saveUrl,
            <?php echo Mage::registry("configuration")->getId(); ?>,
            fetchUrl
        );
    });
</script>